### ISSUE TITLE
200% FED deadtime

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#152]
http://daq-expert.cms/DAQExpert/?start=2017-11-09T14:51:10.610Z&end=2017-11-09T14:59:17.923Z

**Comment by andreh12** [comment]
DAQView (http://daq-expert.cms/daq2view-react/index.html?setup=cdaq&time=2017%2011%2009%2015:55:14) shows:
* FED582 100% in warning
* both FED582 and FED583 100% backpressured by DAQ

**Comment by andreh12** [comment]
The real problem here is actually `SyncLoss` but the error message from the RU has a format slightly different from this one here: https://github.com/cmsdaq/DAQExpert/blob/863bddc0d942661ce72e66f17b7d02581282d608/src/main/java/rcms/utilities/daqexpert/reasoning/logic/failures/backpressure/BackpressureAnalyzer.java#L43-L44

**Comment by andreh12** [comment]
ignore my previous comment, the `SyncLoss` was identified and the FED number was parsed correctly

**Comment by gladky** [comment]
The reason is wrong calculation of `deadPercentage` value. Unnecessary contribution of `percentBackpressure`.

```
float deadPercentage = 0;
deadPercentage += fed.getPercentBackpressure();
deadPercentage += fed.getPercentBusy();
deadPercentage += fed.getPercentWarning();
```

I will deploy the hotfix.

**Comment by gladky** [comment]
Fixed and tested. Pull request #153. Please review it now the calculation is correct.
