### ISSUE TITLE
Failure to parse Syncloss message from RU

### ISSUE THREAD

**Issue by mommsen** [cmsdaq/DAQExpert#57]
See http://cmsonline.cern.ch/cms-elog/978160

**Comment by andreh12** [comment]
from the ELOG message:

```
Run blocked by out-of-sync data from FED (regex mismatch), RU ru-c2e14-29-01.cms is in syncloss. Problem FED belongs to TTCP (regex mismatch) in (regex mismatch) subsystem
```

I'll try to find the original error message and build a test case.

**Comment by mommsen** [comment]
The original message is in above elog entry.

**Comment by andreh7** [comment]
This one I mean:

```
Caught exception: exception::EventOutOfSequence 'Received an event out of sequence from FED 622 (ECAL): The FED trailer indicates that a wrong FED CRC checksum was found by the FEROL (FED trailer R bit is set). Skipped from event number 16466830 to 16728975' raised at reportErrors(/usr/local/src/xdaq/baseline14/trunk/daq/evb/src/common/readoutunit/FedFragment.cc:548)
```
(taken from the json snapshot)

**Comment by andreh12** [comment]
should be contained e.g. in `/daqexpert/snapshots/pro/cdaq/2017/4/27/3/1493263275021.smile`

**Comment by gladky** [comment]
The pattern didn't match because actual error was `EventOutOfSequence` but expected was `MismatchDetected`. LM's pattern is following:

`Caught exception: exception::MismatchDetected 'Mismatch detected: expected evb id`

while in this case the message was:

`Caught exception: exception::EventOutOfSequence 'Received an event out of sequence from FED 622...`

**Comment by andreh12** [comment]
Originally the regexe was designed to also detect the out of sync condition itself and was therefore quite precise. I see now that there is a separate field which actually contains the RU state from which the out of sync condition can be detected.

I will change the code to relax the regex patterns to the minimum e.g. `FED (\d+)` etc. unless there are objections.

**Comment by mommsen** [comment]
I think the DAQ expert could match the actually condition, i.e. any character after 'exception::'.

The difference between EventOutOfSequence  and MismatchDetected is the following: EventOutOfSequence is checking the sequentiality of the event (trigger) numbers. The must be sequential without holes and only reset to 1, or wrap to 0. The MismatchDetected is done as a 2nd step where the received event number is compared to the one received from the EVM. Thus, this test will catch the case where a subsystem sent an event more or less than TCDS.

**Comment by andreh12** [comment]
The purpose of the regex is just to find the FED id which is contained in the error message. The sync loss condition is actually detected first from the fact that the daqstate is run blocked and then the RU is identified as the first RU which has a state 'SyncLoss'.

The regex is merely used to find the FED from the error message. Currently we have the following regex to find the FED number:

```
Pattern.compile("Caught exception: exception::MismatchDetected 'Mismatch detected: expected evb id .*, but found evb id .* in data block from FED (\\d+) \\((.+)\\)' raised at")
```

what I'm proposing is to simplify / generalize this to:

```
Pattern.compile(" FED (\\d+) \\((.+)\\)")
```
i.e. just search for the number after FED and a subsystem in parentheses (even though the logic module currently takes the subsystem and ttc partition from its internal information)

Otherwise we probably would have to add a second regex to match this new case:

```
Pattern.compile("Caught exception: exception::EventOutOfSequence 'Received an event out of sequence from FED (\\d+) \\((.+)\\): ");
```

plus for any message we encounter in the future.

**Comment by andreh12** [comment]
After a quick discussion with @mommsen , we concluded that it is ok to use the short regex pattern just looking for `FED` and a number.

**Comment by hsakulin** [comment]
Hi,

I think it would be good if the full error message of the RU could be displayed at the end of the analysis of the Expert so that details are immediately available.

Cheers,
  Hannes.

**Comment by andreh12** [comment]
@hsakulin do you mean to add the original error message as a parameter to the description e.g. as follows

```
this.description = "Run blocked by out-of-sync data from FED {{FED}}, RU {{RU}} is in syncloss. "
				+ "Problem FED belongs to TTCP {{TTCP}} in {{SUBSYSTEM}} subsystem."
                                + "Original error message: {{ORIGMESSAGE}}";
```
?

**Comment by andreh12** [comment]
added @hsakulin 's suggestion in commit cfe733b (i.e. pull request is updated)

**Comment by andreh12** [comment]
The corresponding pull request #58 fixing this issue went into the 2.5.0 release.
