### ISSUE TITLE
add a logic module for 'RU failed' 

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQExpert#70]
should trigger if

- at least one RU is in failed state
- reason for no rate could not otherwise be identified (i.e. currently `UnidentifiedFailure` would fire)

This module should also put the RU error messages into the message to be displayed.

**Comment by andreh7** [comment]
continuing the discussion from https://github.com/cmsdaq/DAQExpert/pull/72#issuecomment-308416588 here:

- a test case from the same failure period as case 2 (Fri Jun  9 17:21:56 CEST 2017 instead of Fri Jun  9 17:14:42 CEST 2017) is already in the branch to be submitted as pull request soon (in commit 7c9d22e)
- I'll add test case 1

**Comment by andreh12** [comment]
continuing the discussion from https://github.com/cmsdaq/DAQExpert/pull/72#issuecomment-308416588 here:

- a test case from the same failure period as case 2 (Fri Jun  9 17:21:56 CEST 2017 instead of Fri Jun  9 17:14:42 CEST 2017) is already in the branch to be submitted as pull request soon (in commit 7c9d22e)
- I'll add test case 1

**Comment by andreh12** [comment]
added test case 1 in commit 89286c3

**Comment by andreh12** [comment]
the fix #74 was released in 2.9.0
