### ISSUE TITLE
spurious FEROL40 case

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQExpert#76]
this case: http://daq-expert.cms/DAQExpert/?start=2017-06-17T12:42:49.197Z&end=2017-06-17T12:46:49.197Z triggered `FEROLFifoStuck` but should not.

**Comment by andreh12** [comment]
in fact, in the above case, one RU was in `SyncLoss` state but the DAQ state was not `RunBlocked`. 

@mommsen or @hsakulin ,  is this different from what we should detect in `FlowchartCase1` or can we drop the requirement for `RunBlocked` in `FlowchartCase1` ?

**Comment by mommsen** [comment]
I would claim that this is a bug/race condition in the DAQ FM. The RU sent the sync-loss message while DAQ was being enabled:
` 2017-06-17 14:43:39 and 143 ms : cdaq.cms.frlpc-s2d10-21-01.p:11100.ferol::FerolController.instance(400)
      INFO EnableAction needed 56 mu seconds.
 2017-06-17 14:43:39 and 144 ms : cdaq.cms.ru-c2e14-10-01.p:11100.evb::RU.instance(53)
     ERROR SyncLoss: Caught exception: exception::EventOutOfSequence 'Received an event out of sequence from FED 582 (CTPPS_TOT/CTPPS): Received a duplicate event number 0' raised at reportErrors(/usr/lo
cal/src/xdaq/baseline14/trunk/daq/evb/src/common/readoutunit/FedFragment.cc:548)
 2017-06-17 14:43:39 and 145 ms : cdaq.cms.frlpc-s1d06-35-01.p:11100.ferol::FerolController.instance(305)
      INFO EnableAction needed 0 mu seconds.`

I guess the SOAP message from the RU got lost.

**Comment by mommsen** [comment]
BTW: it just happened again:
http://daq-expert.cms/daq2view-react/index.html?setup=cdaq&time=2017-06-19-15:04:35

**Comment by andreh12** [comment]
ok, thanks for checking. That also explains why `FEROLFifoStuck` fired in this case: there is a requirement that DAQ must not be in `RunBlocked` state.

As discussed with @mommsen , I added the requirement that the RU is not in `SyncLoss` state in the `FEROLFifoStuck` module in commit 3403f63 .

**Comment by andreh12** [comment]
I pushed the changes to a new branch `hotfix/spurious-ferol-fifo-stuck` forking from `release/2.8.0`, see https://github.com/cmsdaq/DAQExpert/compare/release/2.8.0...andreh12:hotfix/spurious-ferol-fifo-stuck .

I think this should be put into production as soon as possible in order not to confuse the shifter.

@gladky , should I create a pull request based on `release/2.8.0` or create a branch `release/2.8.1` (based on 2.8.0) and use this as a base branch ?

**Comment by gladky** [comment]
Thank you for the hotfix. It's in production since 17:08.

@andreh12 here is summary of actions (according to [git flow workflow](https://danielkummer.github.io/git-flow-cheatsheet/)):

1. `git flow hotfix start name-of-bugfix` to create a new branch based on current state of master (always production ready state, I merge release branches to master when they are deployed to production) - this basically means that the fixes will be based on the version currently in production
1. The version in pom.xml bumped (in this case to 2.8.1)
1. used you commits as a fix
1.  `git flow hotfix finish name-of-bugfix`. This resulted in merging it to master and also backmerging to dev branch.

**Comment by andreh12** [comment]
thanks a lot @gladky for the instructions and especially for putting this into production so quickly !
